---
title: "fars"
author: "Trevor"
date: "4/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	fig.path='Figs/'
)
```


```{r message=FALSE, warning=FALSE}
library(tidyverse)
crss <- read_csv("/home/data/original/dftwo0408.csv")

crss1 <- crss %>%
  
  dplyr::mutate(
    across(c(AGE1.1,AGE1.2, MANCOLL, INJ_SEV.1, INJ_SEV.2, DRINKING.1, DRINKING.2, 
             AIR_BAG.1, AIR_BAG.2, ROLLOVER.1, ROLLOVER.2, REST_USE.1, REST_USE.2), as.factor),
    across(c(INJ_SEV.1, INJ_SEV.2), ~ fct_inseq(., ordered = TRUE))) %>% 
    drop_na() %>% 
    group_split(LGT, WEATHER2) 
    

```

```{r warning=FALSE}
library(mvord)
pb <- txtProgressBar(style=3)
star_time <- Sys.time() ## 记录程序开始时间

# results = vector("list", length(crss1))
# names(results) = names(crss1)
# s
# for (i in seq_along(crss1)){
#   
#   results[[i]] <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1 + DRUGS.1 +AIR_BAG.1 + EJECTION.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+  DRUGS.2  + AIR_BAG.2+ EJECTION.2 + ROLLOVER.2 + MANCOLL,
#                  threshold.constraints = c(1,2,3,4),
#                  link = mvprobit(),data = crss1[i][[1]])
#    ## 第二个位置：实时反映进度
#   setTxtProgressBar(pb, i/seq_along(crss1))
# }
# 
# end_time <- Sys.time()  ## 记录程序结束时间
# ## 第三个位置关闭进度条
# close(pb)
# run_time <- end_time - star_time  ## 计算程序运行时间
# results




mv1 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,2,3,4),
                  link = mvprobit(),data = crss1[1][[1]])
mv11 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,1,2,2),
                  coef.constraints = c(1,1,2,2),
                  link = mvprobit(),data = crss1[1][[1]])
mv2 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,2,3,4),
                  link = mvprobit(),data = crss1[2][[1]])
mv21 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,1,2,2),
                  coef.constraints = c(1,1,2,2),
                  link = mvprobit(),data = crss1[2][[1]])
mv3 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,2,3,4),
                  link = mvprobit(),data = crss1[3][[1]])
mv31 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,1,2,2),
                  coef.constraints = c(1,1,2,2),
                  link = mvprobit(),data = crss1[3][[1]])
mv4 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,2,3,4),
                  link = mvprobit(),data = crss1[4][[1]])
mv41 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,1,2,2),
                  coef.constraints = c(1,1,2,2),
                  link = mvprobit(),data = crss1[4][[1]])

mv5 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,2,3,4),
                  link = mvprobit(),data = crss1[5][[1]])
mv51 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,1,2,2),
                  coef.constraints = c(1,1,2,2),
                  link = mvprobit(),data = crss1[5][[1]])

mv6 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,2,3,4),
                  link = mvprobit(),data = crss1[6][[1]])
mv61 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1  +AIR_BAG.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+ AIR_BAG.2 + ROLLOVER.2 + MANCOLL,
                  threshold.constraints = c(1,1,2,2),
                  coef.constraints = c(1,1,2,2),
                  link = mvprobit(),data = crss1[6][[1]])
# mvall <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1,INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1 + DRUGS.1 +AIR_BAG.1 + EJECTION.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+  DRUGS.2  + AIR_BAG.2+ EJECTION.2 + ROLLOVER.2 + MANCOLL,
#                   threshold.constraints = c(1,2,3,4),
#                   link = mvlogit(),data = crss)


```

```{r}
# pb <- txtProgressBar(style=3)
# fit1 <- mvord(formula = MMO2(INJ_SEV.1, INJ_SEV.2) ~ 0 + AGE1.1+ DRINKING.1 + AGE1.2 + DRINKING.2,threshold.constraints = c(1,2),
#               link = mvprobit(),data = crss1[5][[1]])
# fit3 <- mvord(formula = MMO2(REST_USE.1, REST_USE.2, INJ_SEV.1, INJ_SEV.2) ~ 0 +AGE1.1+ DRINKING.1 + DRUGS.1 +AIR_BAG.1 + EJECTION.1 + ROLLOVER.1 + AGE1.2 + DRINKING.2+  DRUGS.2  + AIR_BAG.2+ EJECTION.2 + ROLLOVER.2 + MANCOLL,threshold.constraints = c(1,2,3,4),
#               link = mvprobit(),data = crss1[5][[1]])
# 
# setTxtProgressBar(pb)
```

